name: checks
on:
  workflow_dispatch:
    inputs:
      sha:
        type: string
permissions: write-all

jobs:

  test-linux:
    name: test-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch https://github.com/nektos/act HEAD
      - run: git checkout FETCH_HEAD
      - run: git fetch https://github.com/actions-oss/act-cli ${{ inputs.sha }}
      - run: git cherry-pick FETCH_HEAD
      - run: git push origin HEAD:refs/heads/bp-${{ github.run_id }}
