name: checks
on:
  workflow_dispatch:
    inputs:
      sha:
        type: string
permissions: write-all

jobs:

  test-linux:
    name: test-linux
    runs-on: ubuntu-latest
    steps:
      - name: setup git
        run: |
          # from https://github.com/orgs/community/discussions/26560
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - uses: actions/checkout@v4
      - run: git fetch https://github.com/nektos/act HEAD
      - run: git checkout FETCH_HEAD
      - run: git fetch https://github.com/actions-oss/act-cli ${{ inputs.sha }}
      #- run: git cherry-pick FETCH_HEAD
      - run: |
          git cherry-pick --no-commit "FETCH_HEAD"
          
          # Get original commit message
          original_msg=$(git log -1 --pretty=%B "FETCH_HEAD")
          
          # Strip issue number pattern like "(#1234)"
          cleaned_msg=$(echo "$original_msg" | sed -E 's/[[:space:]]*\(#\d+\)[[:space:]]*$//')
          
          # Commit with cleaned message
          git commit -m "$cleaned_msg"
      - run: git push origin HEAD:refs/heads/bp-${{ github.run_id }}
